/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wnondmqmuvjugbomyolz"
export const supabaseUrl = "https://wnondmqmuvjugbomyolz.supabase.co"
// JWT anon key (Settings → API). Edge Functions verify_jwt requires Bearer JWT, not sb_publishable_*.
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indub25kbXFtdXZqdWdib215b2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MTE3NzQsImV4cCI6MjA4ODQ4Nzc3NH0.7CJOTYZ-NhI9XiyWEGpcBxORx4mmM7jxx0MIJ-lQYSc"

// Production mode - use Supabase Edge Functions
export const API_BASE_URL = `https://${projectId}.supabase.co/functions/v1/make-server-27d0d16c`

// Vite dev server proxy base (avoids browser CORS for local development)
export const DEV_API_BASE_URL = `/functions/v1/make-server-27d0d16c`