/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_27d0d16c (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/wnondmqmuvjugbomyolz/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_27d0d16c").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_27d0d16c").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_27d0d16c").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_27d0d16c").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_27d0d16c").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_27d0d16c").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

/** SQL LIKE'da `_` va `%` maxsus  branch_id kalitlarida noto'g'ri moslash bo'lardi. Regex bilan aniq prefiks. */
function prefixToKeyRegex(prefix: string): string {
  const escaped = String(prefix || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return `^${escaped}`;
}

/** Supabase select default ~1000 qator — bitta so'rovda qolgan `house:` / `car:` yozuvlari yo'qolmasligi uchun. */
const KV_PREFIX_PAGE_SIZE = 1000;

async function selectAllRowsByKeyPrefix(
  prefix: string,
): Promise<Array<{ key: string; value: any }>> {
  const supabase = client();
  const regex = prefixToKeyRegex(prefix);
  const out: Array<{ key: string; value: any }> = [];
  let offset = 0;
  for (;;) {
    const { data, error } = await supabase
      .from("kv_store_27d0d16c")
      .select("key, value")
      .filter("key", "match", regex)
      .order("key", { ascending: true })
      .range(offset, offset + KV_PREFIX_PAGE_SIZE - 1);
    if (error) {
      throw new Error(error.message);
    }
    const batch = data ?? [];
    for (const d of batch) {
      const key = String(d.key ?? "");
      if (key.startsWith(prefix)) {
        out.push({ key, value: d.value });
      }
    }
    if (batch.length < KV_PREFIX_PAGE_SIZE) break;
    offset += KV_PREFIX_PAGE_SIZE;
  }
  return out;
}

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const rows = await selectAllRowsByKeyPrefix(prefix);
  return rows.map((r) => r.value);
};

/** Prefix bo'yicha key+value (buyurtmada `id` ba'zan faqat KV kalitida bo'lgani uchun) */
export const getByPrefixWithKeys = async (
  prefix: string,
): Promise<Array<{ key: string; value: any }>> => {
  return selectAllRowsByKeyPrefix(prefix);
};